---
- name: gets URL
  hosts: localhost
  become: true
  become_method: sudo
  user: ec2-user
  tasks:
  - name: get wordpress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/wordpress.tar.gz
      mode: '0440'