--- 
- name: homework task1
  hosts: all
  become: true
  become_method: sudo
  user: ec2-user
  
  tasks: 
  - name: install mariadb prerequisites
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    apt: pkg=software-properties-common update_cache=yes
 
  - name: install mariadb
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    apt: pkg=mariadb-server update_cache=yes
    notify: 
    - Start DB server
    
  handlers:
  - name: Start DB server
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    systemd: 
      name: mariadb 
      state: restarted
      enabled: true