- name: Get node facts
  hosts: localhost
  become: true
  become_method: sudo
  user: ec2-user
  tasks:
  - name: Print facts
    ansible.builtin.debug:
      var: ansible_facts
  - name: Print out
    debug:
      msg: "{{ ansible_facts }}"

  - name: Distro
    ansible.builtin.debug:
      var: ansible_facts['distribution']