---
- name: add users
  hosts: localhost
  become: true
  become_method: sudo
  user: ec2-user
  vars_files:
    - /home/ec2-user/ansible/vars/test2.yaml
      
  tasks:
  - name: add users
    ansible.builtin.user:
      name: "{{ vars_files }}"
      state: present
    # with_items:
    # - ben
    # - john
    # - lisa